export default Images = {
  backgroundSphere: require('../assets/images/img_red_sphere.png'),
  logo: require('../assets/images/img_logo.png'),
  signupBackground: require('../assets/images/img_signup.png'),
  mobile: require('../assets/images/img_mobile.png'),
  backArrow: require('../assets/images/img_back_arrow.png'),
  triangleView: require('../assets/images/img_triangle_view.png'),
  profileOuter: require('../assets/images/img_profile_circle.png'),
  user: require('../assets/images/img_user.png'),
  upload: require('../assets/images/img_profile_upload.png'),
  attention: require('../assets/images/img_attention.png'),
  headerIcon1: require('../assets/images/nav-icon/1.png'),
  headerIcon2: require('../assets/images/nav-icon/2.png'),
  headerIcon3: require('../assets/images/nav-icon/3.png'),
  headerIcon4: require('../assets/images/nav-icon/4.png'),
  welcomeUser: require('../assets/images/img_welcome_user.png'),
};
