export const VERIFY_OTP = 'VERIFY_OTP';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAIL = 'VERIFY_OTP_FAIL';

export const SAVE_COUNTRY_LIST = 'SAVE_COUNTRY_LIST';
export const SAVE_CAR_LIST = 'SAVE_CAR_LIST';

export const SAVE_USER_STEP = 'SAVE_USER_STEP';
